/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-09 at 18:13:30 UTC 
 * Modify at your own risk.
 */

package com.appspot.ocr_backend.backend.model;

/**
 * Response to user creation request ok: (Boolean) Meter creation successful or failed meters:
 * (Meter) Detailed info of each meter error: (String) If creation failed, contains the reason,
 * otherwise empty.
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesGetMetersResponse extends com.google.api.client.json.GenericJson {

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String error;

    /**
     * Message containing the details of a Meter urlsafe_key: (String) urlsafe key account_number:
     * (String) balance: (Integer) model: (String)
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.util.List<MessagesMeter> meters;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.Boolean ok;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getError() {
        return error;
    }

    /**
     * @param error error or {@code null} for none
     */
    public MessagesGetMetersResponse setError(java.lang.String error) {
        this.error = error;
        return this;
    }

    /**
     * Message containing the details of a Meter urlsafe_key: (String) urlsafe key account_number:
     * (String) balance: (Integer) model: (String)
     *
     * @return value or {@code null} for none
     */
    public java.util.List<MessagesMeter> getMeters() {
        return meters;
    }

    /**
     * Message containing the details of a Meter urlsafe_key: (String) urlsafe key account_number:
     * (String) balance: (Integer) model: (String)
     *
     * @param meters meters or {@code null} for none
     */
    public MessagesGetMetersResponse setMeters(java.util.List<MessagesMeter> meters) {
        this.meters = meters;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Boolean getOk() {
        return ok;
    }

    /**
     * @param ok ok or {@code null} for none
     */
    public MessagesGetMetersResponse setOk(java.lang.Boolean ok) {
        this.ok = ok;
        return this;
    }

    @Override
    public MessagesGetMetersResponse set(String fieldName, Object value) {
        return (MessagesGetMetersResponse) super.set(fieldName, value);
    }

    @Override
    public MessagesGetMetersResponse clone() {
        return (MessagesGetMetersResponse) super.clone();
    }

}
