/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-05-06 at 23:19:35 UTC 
 * Modify at your own risk.
 */

package com.appspot.ocr_backend.backend.model;

/**
 * Message containing the result of the processing of an image task_name: (String)
 * Process--[image_name] task_payload: (String) [account_number]--[image_name] result: (Integer) the
 * measurement read from the image. Empty if error error: (String) error. Empty if success
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesImageProcessingResult extends com.google.api.client.json.GenericJson {

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String error;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    @com.google.api.client.json.JsonString
    private java.lang.Long result;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key("task_name")
    private java.lang.String taskName;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key("task_payload")
    private java.lang.String taskPayload;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getError() {
        return error;
    }

    /**
     * @param error error or {@code null} for none
     */
    public MessagesImageProcessingResult setError(java.lang.String error) {
        this.error = error;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Long getResult() {
        return result;
    }

    /**
     * @param result result or {@code null} for none
     */
    public MessagesImageProcessingResult setResult(java.lang.Long result) {
        this.result = result;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getTaskName() {
        return taskName;
    }

    /**
     * @param taskName taskName or {@code null} for none
     */
    public MessagesImageProcessingResult setTaskName(java.lang.String taskName) {
        this.taskName = taskName;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getTaskPayload() {
        return taskPayload;
    }

    /**
     * @param taskPayload taskPayload or {@code null} for none
     */
    public MessagesImageProcessingResult setTaskPayload(java.lang.String taskPayload) {
        this.taskPayload = taskPayload;
        return this;
    }

    @Override
    public MessagesImageProcessingResult set(String fieldName, Object value) {
        return (MessagesImageProcessingResult) super.set(fieldName, value);
    }

    @Override
    public MessagesImageProcessingResult clone() {
        return (MessagesImageProcessingResult) super.clone();
    }

}
